#! /bin/sh
artist=$(playerctl metadata artist)
title=$(playerctl metadata title)
echo "| ${artist::10} – ${title::25} |"
case "$BLOCK_BUTTON" in
	1)
			if playerctl -a status | grep Playing >/dev/null
			then
				playerctl pause
			elif playerctl -a status | grep Paused >/dev/null
                        then
                                playerctl play
                        fi
esac

