#! /bin/sh

SHORTFMT="${SHORTFMT:-+%d.%m.%Y}"
LABEL="${LABEL:-}"
shortblockdate=$(date "$SHORTFMT")

year=$(date '+%Y')
month=$(date '+%m')
case "$BLOCK_BUTTON" in
    1|2|3)
date=$(date '+%A, %d. %B')
export TERM=xterm
cal --color=always $month $year \
    | sed 's/\x1b\[[7;]*m/\<span weight="heavy" foreground="#D97C2B"\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/span\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
	-markup-rows \
        -no-fullscreen \
	-a -3 \
        -hide-scrollbar \
	-theme minimal-calendar \
        -m -3 \
        -no-custom \
        -p "$date" > /dev/null 
    esac
echo "$LABEL$shortblockdate"
